name: Pylint and Deploy to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: pipy
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint twine wheel setuptools build
    - name: Clean dist folder
      run: |
        rm -rf dist
    - name: Analyzing the code with pylint
      run: |
        pylint --disable=E0401 $(git ls-files '*.py')
    - name: Build the package
      run: |
        python -m build
    - name: Test secrets (print the name of the secret)
      run: |
        echo "TWINE_PASSWORD is set to: ${{ secrets.PYPI_TOKEN }}"
    - name: Publish to PyPI
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        python -m twine upload --skip-existing dist/*
