name: Pylint and Deploy to PyPI

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags (e.g., v1.0, v2.0.1)

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv
        pip install pylint
        pip install twine  # Add Twine for uploading to PyPI
    - name: Analyzing the code with pylint
      run: |
        pylint --disable=E0401 $(git ls-files '*.py')
    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel  # Build source and wheel distributions
    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__  # For PyPI token-based authentication
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}  # Your PyPI token from GitHub secrets
      run: |
        twine upload dist/*  # Upload all distributions to PyPI
